# Generated by Django 3.2.11 on 2022-01-17 20:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_flat_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='valid_owners_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
