# Generated by Django 3.2.11 on 2022-01-25 14:26

from django.db import migrations


def get_owners_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner_name = flat.owner
        owners_phone_number = flat.owners_phonenumber
        owners_valid_phonenumber = flat.valid_owners_phonenumber
        Owner.objects.get_or_create(
            name=owner_name,
            phonenumber = owners_phone_number,
            valid_phonenumber = owners_valid_phonenumber
        )


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    owners.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_owner_valid_phonenumber'),
    ]

    operations = [
        migrations.RunPython(get_owners_data, move_backward),
    ]
