# Generated by Django 3.2.11 on 2022-01-25 14:45

from django.db import migrations


def connect_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owners_flats = Flat.objects.filter(owner=owner.name)
        owner.flats.set(owners_flats)


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20220125_1726'),
    ]

    operations = [
        migrations.RunPython(connect_flats_to_owners, move_backward),
    ]
